// <auto-generated />
namespace RMS.Data.DataContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Migrate20 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Migrate20));
        
        string IMigrationMetadata.Id
        {
            get { return "201711271616599_Migrate-20"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
