// <auto-generated />
namespace RMS.Data.DataContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Migrate12 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Migrate12));
        
        string IMigrationMetadata.Id
        {
            get { return "201711232100035_Migrate-12"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
